alias ll='ls -alh'
alias AR='yay -Yc && yes | yay -Scc'
alias dfh='df -h'
alias 'cd..'='cd ..'
alias yt='yt-dlp'
alias ytdl='yt-dlp'
alias vzr='vim ~/.zshrc'
alias wtr='curl wttr.in/Gyula'
alias pipes='pipes.sh -p 11 -r 0 -f 144'
alias s='systemctl'
alias sp='ssh -p 7028 pd@projectdreams.hu'
alias sh='ssh -p 7028 holorum@projectdreams.hu'
alias bb='rsync -arvz -e "ssh -p 7028" --exclude={"/dev/*","/proc/*","/sys/*","/tmp/*","/run/*","/mnt/*","/media/*","/lost+found"} projectdreams.hu:/ /media/backup/dream/'
alias sx='setxkbmap hu && setxkbmap -option caps:swapescape && setxkbmap -option compose:menu'
alias nano='vim'
