alias ls='ls --color=auto'
alias ll='ls -alh'
alias AR='yay -Yc && yes | yay -Scc'
alias dfh='df -h'
alias 'cd..'='cd ..'
alias wtr='curl wttr.in/Gyula'
alias pipes='pipes.sh -p 11 -r 0 -f 144 -R'
alias s='systemctl'
alias sx='setxkbmap hu && setxkbmap -option caps:swapescape && setxkbmap -option compose:menu'
alias nano='vim'
